# ใช้ Python 3.10 เป็น base image
FROM python:3.8

# ติดตั้ง dependencies ที่จำเป็น
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    python3-dev \
    python3-pip \
    libboost-all-dev \
    libopenblas-dev \
    liblapack-dev \
    libx11-dev \
    libgtk-3-dev \
    libatlas-base-dev \
    default-libmysqlclient-dev \
    && rm -rf /var/lib/apt/lists/*

# ตั้งค่าตัวแปร environment
ENV PYTHONUNBUFFERED=1

# ตั้งค่าโฟลเดอร์ทำงาน
WORKDIR /app

# คัดลอก requirements.txt และติดตั้ง dependencies
COPY req.txt /app/
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r req.txt

# คัดลอกโค้ดทั้งหมดเข้า container
COPY . /app/

# รันเซิร์ฟเวอร์ Django
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

