

services:
  web:
    build: .
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=webadmin
      - DATABASE_USER=root
      - DATABASE_PASSWORD=Narathip998900@
      - DATABASE_HOST=db
      - DATABASE_PORT=3306

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: webadmin
      MYSQL_ROOT_PASSWORD: Narathip998900@
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: Narathip998900@
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  mysql_data: